// DESIGN.md: a product's design rules as one Markdown file, for the people
// and coding agents who build a mocked feature for real. It says which
// library the product is built on, its measured tokens, its components with
// their real class names, its layout, and the rules a new screen follows,
// and it is honest about provenance: measured values are labelled measured,
// roles guessed from usage are labelled inferred. Built from what Page
// Bender already holds: the capture's style census, its detected libraries
// and parts, and the product's learned design system when there is one.
import fs from "node:fs";
import path from "node:path";
import { detectLibraries, pageParts } from "./page-ds.js";
import { designSystemParts } from "./ds-parts.js";
import { pageOutline, screensIn } from "./outline.js";

const hex = (v) => {
  const m = String(v).match(/rgba?\(\s*(\d+),\s*(\d+),\s*(\d+)(?:,\s*([\d.]+))?/);
  if (!m) return String(v);
  const h = "#" + [m[1], m[2], m[3]].map((n) => Number(n).toString(16).padStart(2, "0")).join("");
  return m[4] != null && Number(m[4]) < 1 ? `${h} at ${Math.round(Number(m[4]) * 100)}%` : h;
};
const rgb = (v) => (String(v).match(/\d+(\.\d+)?/g) || []).map(Number);
// How colourful a colour is: tells an accent from greys.
const chroma = (v) => { const [r, g, b] = rgb(v); return r == null ? 0 : Math.max(r, g, b) - Math.min(r, g, b); };
const light = (v) => { const [r, g, b] = rgb(v); return r == null ? 0 : (r + g + b) / 3; };
const row = (cells) => `| ${cells.join(" | ")} |`;
const firstClass = (markup) => ((markup.match(/^<[^>]*class="([^"]*)"/) || [, ""])[1]).split(/\s+/).filter(Boolean).slice(0, 3).join(" ");

// Colour roles from how often and where each colour is used. Guesses, and
// labelled as such.
function colourRoles(c) {
  const roles = [];
  const text = c.textColors || [];
  const bgs = c.backgrounds || [];
  if (c.body) roles.push(["Page background", hex(c.body.background), "measured on <body>"]);
  if (text[0]) roles.push(["Body text", hex(text[0].value), "most-used text colour"]);
  const accent = text.find((t) => chroma(t.value) > 60);
  if (accent) roles.push(["Accent / links", hex(accent.value), "most-used colourful text"]);
  const muted = text.find((t, i) => i > 0 && chroma(t.value) < 30 && t !== accent && light(t.value) > 70 && light(t.value) < 200);
  if (muted) roles.push(["Muted text", hex(muted.value), "secondary grey text"]);
  const surface = bgs.find((b) => light(b.value) > 230);
  if (surface) roles.push(["Surface", hex(surface.value), "most-used light background"]);
  const dark = bgs.find((b) => light(b.value) < 90 && !/0\.\d/.test(b.value));
  if (dark) roles.push(["Dark surface (e.g. navigation)", hex(dark.value), "most-used dark background"]);
  if (c.borders && c.borders[0]) roles.push(["Divider / border", c.borders[0].value.replace(/rgba?\([^)]*\)/, (x) => hex(x)), "most-used border"]);
  return roles;
}

export function buildDesignMd({ dir, meta, html, census, ds }) {
  const libs = detectLibraries(html);
  const lib = libs.find((l) => !l.styling);
  const styling = libs.filter((l) => l.styling);
  const date = (meta.capturedAt || new Date().toISOString()).slice(0, 10);
  let host = "";
  try { host = new URL(meta.url).host; } catch {}
  const name = meta.productLabel || (meta.title ? meta.title.split(/[|·–-]/)[0].trim() : host) || "This product";
  const kind = ds && ds.full ? "learned design system" : "page-level read";
  const out = [];

  out.push(`# ${name}: design rules`, "");
  out.push(`Generated by Page Bender on ${new Date().toISOString().slice(0, 10)} from a capture of ${meta.url ? `\`${meta.url}\`` : "a page"} (${date}). ` +
    (ds && ds.full
      ? `It combines that page with the product's learned design system (${ds.full.date}, ${ds.full.pages || "several"} pages, ${ds.full.components} components).`
      : `It is a page-level read: everything here was measured on that one page, so components the page doesn't show are not listed.`), "");
  out.push(`**How to use it:** build new UI with the library and components below, and take every colour, size, radius and spacing from the tokens. Don't introduce values the product doesn't use. Values marked *measured* come from the live page's computed styles; roles marked *inferred* are guesses from usage.`, "");

  out.push("## Built with", "");
  if (lib) {
    out.push(`- **Component library:** ${lib.name} (recognised from ${lib.count} class names on the page). Use its components rather than hand-built equivalents.`);
    for (const l of libs.filter((x) => !x.styling && x !== lib)) out.push(`- Also present: ${l.name} (${l.count} class names).`);
  } else {
    out.push("- **Component library:** none recognised; the product uses its own components and hand-written CSS.");
  }
  for (const s of styling) out.push(`- **Styling:** ${s.name}. Class names like \`sc-…\` are generated; target components by structure or data attributes, not by those classes.`);
  out.push("");

  if (ds && ds.full && ds.familiesNote) {
    out.push("## Style families", "", ds.familiesNote, "", "A new screen uses one family throughout: the family of the page it extends, or the product's newest for a new area.", "");
  }

  if (census) {
    out.push("## Colour", "", row(["Role", "Value", "Source"]), row(["---", "---", "---"]));
    for (const [role, v, src] of colourRoles(census)) out.push(row([role, `\`${v}\``, `${src} (inferred)`]));
    out.push("", "All text colours by use (*measured*): " + (census.textColors || []).slice(0, 8).map((t) => `\`${hex(t.value)}\``).join(", "), "");
    out.push("All backgrounds by use (*measured*): " + (census.backgrounds || []).slice(0, 8).map((t) => `\`${hex(t.value)}\``).join(", "), "");

    out.push("## Typography", "");
    if (census.fontFamilies && census.fontFamilies.length) out.push(`- **Families** (*measured*, by characters set): ${census.fontFamilies.slice(0, 3).map((f) => `\`${f.value}\``).join("; ")}`);
    if (census.body) out.push(`- **Body:** ${census.body.fontSize}, ${census.body.fontFamily}`);
    out.push("", row(["Size", "Weight", "Line height", "Use"]), row(["---", "---", "---", "---"]));
    for (const t of (census.typeScale || []).slice(0, 8)) {
      const [size, weight, lh] = t.value.split(" / ");
      out.push(row([size, weight, lh, `${t.count} characters`]));
    }
    out.push("");

    out.push("## Shape and spacing", "");
    if (census.radii && census.radii.length) out.push(`- **Corner radii** (*measured*, by use): ${census.radii.slice(0, 6).map((r) => `\`${r.value}\``).join(", ")}`);
    if (census.borders && census.borders.length) out.push(`- **Borders:** ${census.borders.slice(0, 4).map((b) => `\`${b.value.replace(/rgba?\([^)]*\)/, (x) => hex(x))}\``).join(", ")}`);
    if (census.shadows && census.shadows.length) out.push(`- **Shadows:** ${census.shadows.slice(0, 3).map((s) => `\`${s.value}\``).join(", ")}`);
    if (census.paddings && census.paddings.length) out.push(`- **Paddings:** ${census.paddings.slice(0, 6).map((p) => `\`${p.value}\``).join(", ")}`);
    if (census.gaps && census.gaps.length) out.push(`- **Gaps:** ${census.gaps.slice(0, 5).map((g) => `\`${g.value}\``).join(", ")}`);
    out.push("");
  }

  if (ds && ds.full && ds.tokensCss) {
    out.push("## Product tokens", "", `Measured across the product (${ds.full.date}), as CSS custom properties:`, "", "```css", ds.tokensCss.trim(), "```", "");
  }

  const outline = pageOutline(html);
  if (outline) {
    out.push("## Layout", "");
    for (const l of outline) out.push(`- **${l.role === "nav" ? "Navigation" : l.role === "header" ? "Header" : "Main content"}:** \`${l.openTag.replace(/\s(style|data-pb-landmark)="[^"]*"/g, "").slice(0, 140)}\`${l.labels && l.labels.length ? `, items: ${l.labels.slice(0, 12).join(", ")}` : ""}`);
    out.push("", "New screens keep the navigation and header and replace only the main content area.", "");
  }

  out.push("## Components", "");
  const fullParts = ds && ds.full ? designSystemParts(ds.full.dir, ds.components || []) : [];
  const parts = fullParts.length
    ? fullParts.map((p) => ({ kind: p.name, family: p.family, page: p.page, markup: p.markup }))
    : pageParts(html).map((p) => ({ kind: p.kind, markup: p.markup }));
  if (!parts.length) out.push("No components were recognised on this page.", "");
  for (const p of parts) {
    out.push(`### ${p.kind}${p.family ? ` (${p.family} family${p.page ? `, from ${p.page}` : ""})` : ""}`, "");
    if (p.markup) {
      const cls = firstClass(p.markup);
      if (cls) out.push(`Root classes: \`${cls}\``, "");
      if (p.markup.length <= 1500) out.push("```html", p.markup.replace(/\sstyle="[^"]*"/g, ""), "```", "");
      else out.push(`Example omitted (${p.markup.length} characters); see the mock for one in place.`, "");
    } else {
      out.push("Too large to include; see the mock for one in place.", "");
    }
  }

  out.push("## Rules for new UI", "");
  out.push(`- Build with ${lib ? lib.name : "the product's own"} components; copy the examples above before inventing anything.`);
  out.push("- Take every value from the tables above. A colour, size, radius or shadow that isn't listed doesn't belong.");
  out.push("- Keep one visual family per screen.");
  out.push("- A component the product doesn't have is designed in its language, from the closest one it does have.");
  out.push("");

  const screens = screensIn(html);
  if (screens.length) out.push("## Screens in the accompanying mock", "", screens.map((s) => `- ${s}`).join("\n"), "");
  out.push(`*Page Bender (${kind}). Measured values reflect the page as captured on ${date}; check against the live product before relying on an exact value.*`, "");
  return out.join("\n").replace(/\n{3,}/g, "\n\n");
}

// Loads what buildDesignMd needs for one mock folder.
export function designMdFor(dir, { designSystemInfo }) {
  const meta = JSON.parse(fs.readFileSync(path.join(dir, "meta.json"), "utf8"));
  const html = fs.readFileSync(path.join(dir, "working.html"), "utf8");
  let census = null;
  try { census = JSON.parse(fs.readFileSync(path.join(dir, "census.json"), "utf8")); } catch {}
  let ds = null;
  const info = meta.product ? designSystemInfo(meta.product) : null;
  if (info && info.full) {
    let index = { components: [], pages: [] };
    try { index = JSON.parse(fs.readFileSync(path.join(info.full.dir, "raw", "index.json"), "utf8")); } catch {}
    let tokens = {};
    try { tokens = JSON.parse(fs.readFileSync(path.join(info.full.dir, "tokens.json"), "utf8")); } catch {}
    let tokensCss = "";
    try { tokensCss = fs.readFileSync(path.join(info.full.dir, "tokens.css"), "utf8"); } catch {}
    ds = { full: info.full, components: index.components, familiesNote: tokens.familiesNote || "", tokensCss: tokensCss.length < 12000 ? tokensCss : "" };
  }
  return buildDesignMd({ dir, meta, html, census, ds });
}
